server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: centene
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update